defmodule Plausible.Graphqla.Types.CustomMetricTypeTest do
  use Plausible.DataCase, async: true

  alias Plausible.Graphqla.Schema
  alias Plausible.Graphqla.Types.CustomMetricTypes

  describe "custom_metric object type" do
    test "defines the correct fields" do
      # Get the custom_metric object type from the schema
      custom_metric_type = Schema.object_type(:custom_metric)

      assert custom_metric_type != nil

      # Check that all expected fields are defined
      field_names =
        custom_metric_type.fields
        |> Map.keys()

      assert :id in field_names
      assert :timestamp in field_names
      assert :name in field_names
      assert :value in field_names
      assert :site_id in field_names
    end

    test "id field is non-null" do
      custom_metric_type = Schema.object_type(:custom_metric)
      id_field = Map.get(custom_metric_type.fields, :id)

      assert id_field.non_null == true
    end

    test "timestamp field is non-null" do
      custom_metric_type = Schema.object_type(:custom_metric)
      timestamp_field = Map.get(custom_metric_type.fields, :timestamp)

      assert timestamp_field.non_null == true
    end

    test "name field is non-null string" do
      custom_metric_type = Schema.object_type(:custom_metric)
      name_field = Map.get(custom_metric_type.fields, :name)

      assert name_field.non_null == true
      assert name_field.type == :string
    end

    test "value field is non-null float" do
      custom_metric_type = Schema.object_type(:custom_metric)
      value_field = Map.get(custom_metric_type.fields, :value)

      assert value_field.non_null == true
      assert value_field.type == :float
    end

    test "site_id field is non-null" do
      custom_metric_type = Schema.object_type(:custom_metric)
      site_id_field = Map.get(custom_metric_type.fields, :site_id)

      assert site_id_field.non_null == true
    end
  end

  describe "custom_metric_filter_input input type" do
    test "defines the correct fields" do
      # Get the input type from the schema
      filter_input = Schema.input_object(:custom_metric_filter_input)

      assert filter_input != nil

      field_names =
        filter_input.fields
        |> Map.keys()

      assert :site_id in field_names
      assert :date_range in field_names
      assert :metric_name in field_names
    end

    test "site_id field is non-null" do
      filter_input = Schema.input_object(:custom_metric_filter_input)
      site_id_field = Map.get(filter_input.fields, :site_id)

      assert site_id_field.non_null == true
    end

    test "date_range field is nullable date_range_input" do
      filter_input = Schema.input_object(:custom_metric_filter_input)
      date_range_field = Map.get(filter_input.fields, :date_range)

      assert date_range_field.non_null == nil
      assert date_range_field.type == :date_range_input
    end

    test "metric_name field is nullable string" do
      filter_input = Schema.input_object(:custom_metric_filter_input)
      metric_name_field = Map.get(filter_input.fields, :metric_name)

      assert metric_name_field.non_null == nil
      assert metric_name_field.type == :string
    end
  end

  describe "CustomMetricTypes module" do
    test "module compiles successfully" do
      assert is_atom(CustomMetricTypes)
    end

    test "defines custom_metric_filter_input" do
      # The module should define the input object
      # We verify by checking the schema includes it
      filter_input = Schema.input_object(:custom_metric_filter_input)
      assert filter_input != nil
    end

    test "defines custom_metric object" do
      # The module should define the object type
      # We verify by checking the schema includes it
      custom_metric_type = Schema.object_type(:custom_metric)
      assert custom_metric_type != nil
    end
  end

  describe "field resolution" do
    test "can resolve custom metric struct to GraphQL format" do
      # Create a mock custom metric struct
      custom_metric = %{
        id: "123",
        timestamp: DateTime.utc_now(),
        name: "revenue",
        value: 100.50,
        site_id: "456"
      }

      # Verify the struct has all required fields for resolution
      assert Map.has_key?(custom_metric, :id)
      assert Map.has_key?(custom_metric, :timestamp)
      assert Map.has_key?(custom_metric, :name)
      assert Map.has_key?(custom_metric, :value)
      assert Map.has_key?(custom_metric, :site_id)
    end
  end

  describe "connection type" do
    test "custom_metric_connection is defined in schema" do
      # Connection types are automatically generated by Absinthe
      # Verify the connection node type exists
      connection_type = Schema.connection(:custom_metric)

      # Absinthe should have created the connection
      assert connection_type != nil
    end
  end
end
